CREATE TABLE default.mf_providers
(
    `npi` Int32 COMMENT 'The National Provider Identifier (NPI) is a unique identification number for healthcare providers used for billing and identification purposes.. Samples: ["{\'npi\': 1003000522}", "{\'npi\': 1003000530}", "{\'npi\': 1003000704}"]',
    `docId` Nullable(String) COMMENT 'A unique identifier for a document associated with the provider, which can be used for referencing specific documents or records.. Samples: ["{\'docId\': \'8933264\'}", "{\'docId\': \'8642563\'}", "{\'docId\': \'12943480\'}"]',
    `personId` Nullable(Int32) COMMENT 'An optional identifier linking the provider to a specific person in the database, useful for managing provider-specific data.. Samples: ["{\'personId\': 12940465}", "{\'personId\': 7623843}", "{\'personId\': 10178928}"]',
    `name` Nullable(String) COMMENT 'The full name of the healthcare provider, helping to identify them in a user-friendly way.. Samples: ["{\'name\': \'Ardalan Enkeshafi\'}", "{\'name\': \'Rashid Khalil\'}", "{\'name\': \'Anna C. Morgan\'}"]',
    `displayName` Nullable(String) COMMENT 'A name intended for display, which may differ from the provider\'s legal name and can be formatted for user-friendly viewing.. Samples: ["{\'displayName\': \'Dr. Carolina P. Larmeu\'}", "{\'displayName\': \'Dr. Michelle E. Romeo\'}", "{\'displayName\': \'Dr. Daniel L. Cornish\'}"]',
    `initials` Nullable(String) COMMENT 'The initials of the healthcare provider, often used in documents or professional settings for brevity.. Samples: ["{\'initials\': \'DE\'}", "{\'initials\': \'KT\'}", "{\'initials\': \'SC\'}"]',
    `familyName` Nullable(String) COMMENT 'The last name of the provider, which is commonly used for identification and search purposes.. Samples: ["{\'familyName\': \'Dr. Enkeshafi\'}", "{\'familyName\': \'Dr. Khalil\'}", "{\'familyName\': \'Dr. Morgan\'}"]',
    `score` Nullable(Float32) COMMENT 'A score representing the provider\'s performance or quality, potentially based on patient feedback or other metrics.. Samples: ["{\'score\': 27.735431671142578}", "{\'score\': 41.36767578125}", "{\'score\': 37.84454345703125}"]',
    `phone` Nullable(String) COMMENT 'The contact phone number for the healthcare provider, essential for patient communications.. Samples: ["{\'phone\': \'706-769-0005\'}", "{\'phone\': \'800-230-4565\'}", "{\'phone\': \'404-778-5299\'}"]',
    `isUSPrescriber` Nullable(Bool) COMMENT 'A boolean value indicating whether the provider is authorized to prescribe medications in the United States.. Samples: ["{\'isUSPrescriber\': True}"]',
    `sex` Nullable(String) COMMENT 'The gender of the healthcare provider, which can be relevant for patient preferences and demographic statistics.. Samples: ["{\'sex\': \'F\'}", "{\'sex\': \'M\'}"]',
    `image` Nullable(String) COMMENT 'A URL link to an image of the healthcare provider, often used in profiles to enhance visual identification.. Samples: ["{\'image\': \'https://cdn.medifind.com/imgrepo/205734\'}", "{\'image\': \'https://cdn.medifind.com/imgrepo/203894\'}", "{\'image\': \'https://cdn.medifind.com/imgrepo/212690\'}"]',
    `primaryOrgName` Nullable(String) COMMENT 'The name of the primary organization or employer associated with the provider, giving context to their practice.. Samples: ["{\'primaryOrgName\': \'Mary Washington Medical Group Hospitalist Services, LLC\'}", "{\'primaryOrgName\': \'Sylvania Pain Medicine\'}", "{\'primaryOrgName\': \'Oakland Medical Center\'}"]',
    `primaryOrgWebsite` Nullable(String) COMMENT 'The website URL of the primary organization, allowing users to access more information about the provider\'s place of employment.. Samples: ["{\'primaryOrgWebsite\': \'https://www.adventhealth.com/practices/adventhealth-medical-group\'}", "{\'primaryOrgWebsite\': \'https://www.slhn.org/\'}", "{\'primaryOrgWebsite\': \'www.kch.org\'}"]',
    `highlyRatedConditionsCount` Nullable(Int32) COMMENT 'The count of medical conditions for which the provider has received high ratings, reflecting their areas of expertise.. Samples: ["{\'highlyRatedConditionsCount\': 3}", "{\'highlyRatedConditionsCount\': 4}", "{\'highlyRatedConditionsCount\': 11}"]',
    `orgLogo` Nullable(String) COMMENT 'A URL link to the logo of the provider\'s organization, used for branding purposes in directories or listings.. Samples: ["{\'orgLogo\': \'https://cdn.medifind.com/orgs/MayoClinic\'}", "{\'orgLogo\': \'https://cdn.medifind.com/orgs/ClevelandClinic\'}", "{\'orgLogo\': \'https://cdn.medifind.com/orgs/WeillCornellMedicine\'}"]',
    `orgWebsite` Nullable(String) COMMENT 'The website URL of the provider\'s affiliated organization, where additional information and resources may be available.. Samples: ["{\'orgWebsite\': \'https://www.stmaryshealthcaresystem.org/medical-group/\'}", "{\'orgWebsite\': \'www.paeyes.com/\'}", "{\'orgWebsite\': \'www.emoryhealthcare.org/\'}"]',
    `healthSystem_website` Nullable(String) COMMENT 'The website of the healthcare system the provider is associated with, providing a broader context for their services.. Samples: ["{\'healthSystem_website\': \'www.marywashingtonhealthcare.com/\'}", "{\'healthSystem_website\': \'www.mercy.com\'}", "{\'healthSystem_website\': \'thrive.kaiserpermanente.org/care-near-you/northern-california/\'}"]',
    `healthSystem_name` Nullable(String) COMMENT 'The name of the healthcare system, useful for understanding the organizational structure in which the provider operates.. Samples: ["{\'healthSystem_name\': \'Piedmont Healthcare System\'}", "{\'healthSystem_name\': \'Geisinger\'}", "{\'healthSystem_name\': \'Emory Healthcare\'}"]',
    `codingCount` Nullable(Int32) COMMENT 'The count of instances where medical coding is applied for the provider, indicating their activity level in documentation.. Samples: ["{\'codingCount\': 35}", "{\'codingCount\': 16}", "{\'codingCount\': 25}"]',
    `biography` Nullable(String) COMMENT 'A brief biography of the healthcare provider, summarizing their background, expertise, and practice focus.. Samples: ["{\'biography\': \'<p>Ardalan Enkeshafi is an Internal Medicine doctor in Bethesda, Maryland. Dr. Enkeshafi has been practicing medicine for over 29 years and is highly rated in 1 condition, according to our data. His top areas of expertise are Sepsis, Peptic Ulcer, Necrosis, and Acute Kidney Failure. Dr. Enkeshafi is currently accepting new patients.</p>\'}", "{\'biography\': \'<p>Rashid Khalil is an Anesthesiologist and a Pain Medicine doctor in Toledo, Ohio. Dr. Khalil has been practicing medicine for over 24 years and is highly rated in 5 conditions, according to our data. His top areas of expertise are Chronic Pain, Spinal Stenosis, Sciatica, and Cervical Spondylosis. Dr. Khalil is currently accepting new patients.</p>\'}", "{\'biography\': \'<p>Anna Morgan is a Pediatrics doctor in Oakland, California.</p>\'}"]',
    `gradInstitution_year` Nullable(Int32) COMMENT 'The year the provider graduated from their medical education institution, indicating their duration of practice.. Samples: ["{\'gradInstitution_year\': 2005}", "{\'gradInstitution_year\': 1999}", "{\'gradInstitution_year\': 2001}"]',
    `gradInstitution_gradYearNumber` Nullable(Int32) COMMENT 'The year number in which the provider completed their degree, providing context on their educational timeline.. Samples: ["{\'gradInstitution_gradYearNumber\': 1994}", "{\'gradInstitution_gradYearNumber\': 1999}", "{\'gradInstitution_gradYearNumber\': 1997}"]',
    `gradInstitution_name` Nullable(String) COMMENT 'The name of the educational institution where the provider graduated, valuable for verifying qualifications.. Samples: ["{\'gradInstitution_name\': \'Other\'}", "{\'gradInstitution_name\': \'Ohio State University College Of Medicine\'}", "{\'gradInstitution_name\': \'State University Of New York At Buffalo School Of Medicine\'}"]',
    `trainingInstitution_year` Nullable(Int32) COMMENT 'The year the provider completed their training, which may reflect their level of expertise in their specialty.. Samples: []',
    `trainingInstitution_gradYearNumber` Nullable(Int32) COMMENT 'The year number for the provider\'s completion of training, offering insights into their professional development.. Samples: []',
    `trainingInstitution_name` Nullable(String) COMMENT 'The name of the training institution where the provider received their postgraduate education, adding to their credentials.. Samples: []'
)
ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY npi
SETTINGS index_granularity = 8192
COMMENT 'This table contains detailed information about healthcare providers, including their personal details, qualifications, affiliations, and contact information.';