CREATE TABLE default.fct_pharmacy_clear_claim_allstatus_cluster_brand
(
    `RX_ANCHOR_DD` Date32,
    `RX_CLAIM_NBR` String,
    `PATIENT_ID` String,
    `SERVICE_DATE_DD` Date32,
    `TRANSACTION_STATUS_NM` String,
    `REJECT_REASON_1_CD` String,
    `REJECT_REASON_1_DESC` String,
    `NDC` String,
    `NDC_DESC` String,
    `NDC_GENERIC_NM` String,
    `NDC_PREFERRED_BRAND_NM` String,
    `NDC_DOSAGE_FORM_NM` String,
    `NDC_DRUG_FORM_NM` String,
    `NDC_DRUG_NM` String,
    `NDC_DRUG_SUBCLASS_NM` String,
    `NDC_DRUG_CLASS_NM` String,
    `NDC_DRUG_GROUP_NM` String,
    `NDC_ISBRANDED_IND` String,
    `PRESCRIBED_NDC` String,
    `DIAGNOSIS_CD` String,
    `DAW_CD` Int64,
    `UNIT_OF_MEASUREMENT_CD` String,
    `PRESCRIBER_NBR_QUAL_CD` String,
    `PRESCRIBER_NPI_NBR` String,
    `PRESCRIBER_NPI_NM` String,
    `PRESCRIBER_NPI_ENTITY_CD` Int64,
    `PRESCRIBER_NPI_HCO_CLASS_OF_TRADE_DESC` String,
    `PRESCRIBER_NPI_HCP_SEGMENT_DESC` String,
    `PRESCRIBER_NPI_STATE_CD` String,
    `PRESCRIBER_NPI_ZIP5_CD` String,
    `PAYER_ID` Int64,
    `PAYER_PAYER_NM` String,
    `PAYER_COB_SEQ_VAL` Int64,
    `PAYER_PLAN_SUBCHANNEL_CD` String,
    `PAYER_PLAN_SUBCHANNEL_NM` String,
    `PAYER_PLAN_CHANNEL_CD` String,
    `PAYER_PLAN_CHANNEL_NM` String,
    `PAYER_COMPANY_NM` String,
    `PAYER_MCO_ISSUER_ID` String,
    `PAYER_MCO_ISSUER_NM` String,
    `PAYER_BIN_NBR` String,
    `PAYER_PCN_NBR` String,
    `PAYER_GROUP_STR` String,
    `FILL_NUMBER_VAL` Int64,
    `DISPENSED_QUANTITY_VAL` Decimal(38, 9),
    `PRESCRIBED_QUANTITY_VAL` Decimal(38, 9),
    `DAYS_SUPPLY_VAL` Decimal(38, 9),
    `NUMBER_OF_REFILLS_AUTHORIZED_VAL` Int64,
    `GROSS_DUE_AMT` Decimal(38, 9),
    `TOTAL_PAID_AMT` Decimal(38, 9),
    `PATIENT_TO_PAY_AMT` Decimal(38, 9),
    `AWP_UNIT_PRICE_AMT` Float64,
    `AWP_CALC_AMT` Float64
)
ENGINE = SharedMergeTree('/clickhouse/tables/{uuid}/{shard}', '{replica}')
ORDER BY (NDC_PREFERRED_BRAND_NM, DIAGNOSIS_CD)
SETTINGS index_granularity = 8192;