[theme]
primaryColor = "#0066cc"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
serverAddress = "localhost"
serverPort = 8501
